version: '3.8'

services:
  lwandi-ui:
    image: lucasfs/lwandi-ui
    container_name: lwandi-ui
    restart: always
    volumes:
      - ./log:/var/log/nginx
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=lwandisurf.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=lwandisurf.org
      - LETSENCRYPT_EMAIL=admin@growtechnologies.com.br

    ports:
      - "3000:80"

networks:
  proxy:
    external:
      name: nginx-proxy
