version: '3.3'

services:
  react-lwandi:
    container_name: react-lwandi
    hostname: react-lwandi
    restart: always
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
      - target: 3000
        published: 3000
        mode: host